# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20171109_1946'),
        ('hub', '0002_auto_20171110_0038'),
    ]

    operations = [
    ]
