# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_merge_20171109_2041'),
        ('hub', '0005_merge_20171109_2013'),
    ]

    operations = [
    ]
