# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_auto_20171121_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
