# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_merge_20171111_1309'),
        ('hub', '0009_rsvp'),
    ]

    operations = [
    ]
