# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_rsvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='date',
        ),
    ]
