# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_auto_20171121_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdetails',
            name='org_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'orgs'),
        ),
        migrations.AddField(
            model_name='organizationdetails',
            name='user_name',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
