# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_auto_20171126_1603'),
        ('hub', '0010_merge_20171125_1750'),
    ]

    operations = [
    ]
