# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_auto_20171126_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='org_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hub.OrganizationDetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationdetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='organizationdetails',
            name='org_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='orgs'),
        ),
        migrations.AlterField(
            model_name='organizationdetails',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
