# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_auto_20171205_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='org_id',
            new_name='org',
        ),
    ]
