# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_auto_20171205_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
