# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_remove_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdetails',
            name='org_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
