# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0016_organizationdetails_org_name'),
        ('hub', '0013_merge_20171126_1735'),
    ]

    operations = [
    ]
