# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_auto_20171205_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='events',
            field=models.ManyToManyField(to='hub.Event'),
        ),
    ]
