# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_auto_20171206_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='hub.Category'),
        ),
    ]
